/* eslint-disable */
/* AUTO-GENERATED by scripts/build-docs.ts — do NOT edit by hand. */
import type {
  DocAnchor,
  DocCategoryNode,
  DocEntry,
  DocLocale,
  DocMeta,
  DocTree,
} from "~/lib/docs/types";

export type {
  DocAnchor,
  DocCategoryNode,
  DocEntry,
  DocLocale,
  DocMeta,
  DocTree,
};

export const trees: Record<DocLocale, DocTree> = {
  "zh": {
    "root": {
      "name": "root",
      "title": "root",
      "children": [
        {
          "name": "software",
          "title": "软件文档",
          "order": 1,
          "children": [],
          "docs": [
            {
              "path": "software/getting-started",
              "meta": {
                "title": "快速开始",
                "description": "五分钟上手环回云",
                "order": 1,
                "navIgnore": false
              },
              "html": "<h1>快速开始</h1>\n<h2>安装</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">pnpm add loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">npm i loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2>配置</h2>\n<p>:::details[展开查看配置文件示例]</p>\n<pre><code class=\"language-toml\">[loopback]\naddr = \"127.0.0.1\"\n</code></pre>\n<p>:::</p>\n<p>:::warning\n不要把 <code>addr</code> 改成本机物理网卡地址，否则\"绝对安全\"卖点会失效。\n:::</p>",
              "anchors": []
            },
            {
              "path": "software/zh-only",
              "meta": {
                "title": "仅中文文档",
                "description": "用于回退测试",
                "order": 9,
                "navIgnore": false
              },
              "html": "<h1>仅中文文档</h1>\n<p>本文档故意只在中文版提供，用于验证缺失英文时的回退渲染。</p>",
              "anchors": []
            }
          ]
        }
      ],
      "docs": []
    },
    "indexDoc": {
      "path": "",
      "meta": {
        "title": "文档首页",
        "description": "环回云文档中心",
        "navIgnore": true
      },
      "html": "<h1>环回云文档</h1>\n<p>欢迎来到环回云文档中心。这里收录了产品使用指南、系统架构与开发文档。</p>\n<h2>导览</h2>\n<p>左侧栏按分类浏览，右侧栏显示当前页面锚点。</p>\n<p>:::note\n本站所有\"云服务\"均在 <code>127.0.0.1</code> 上运行。\n:::</p>",
      "anchors": []
    }
  },
  "en": {
    "root": {
      "name": "root",
      "title": "root",
      "children": [
        {
          "name": "software",
          "title": "Software Docs",
          "order": 1,
          "children": [],
          "docs": [
            {
              "path": "software/getting-started",
              "meta": {
                "title": "Quick Start",
                "description": "Get going with Loopback Cloud in five minutes",
                "order": 1,
                "navIgnore": false
              },
              "html": "<h1>Quick Start</h1>\n<h2>Install</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">pnpm add loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">npm i loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2>Configuration</h2>\n<p>:::details[Expand for an example config]</p>\n<pre><code class=\"language-toml\">[loopback]\naddr = \"127.0.0.1\"\n</code></pre>\n<p>:::</p>\n<p>:::warning\nDo not change <code>addr</code> to a physical NIC, or the \"absolutely secure\" claim breaks.\n:::</p>",
              "anchors": []
            }
          ]
        }
      ],
      "docs": []
    },
    "indexDoc": {
      "path": "",
      "meta": {
        "title": "Docs Home",
        "description": "Loopback Cloud documentation",
        "navIgnore": true
      },
      "html": "<h1>Loopback Cloud Docs</h1>\n<p>Welcome to the Loopback Cloud documentation center.</p>\n<h2>Navigation</h2>\n<p>Browse categories in the left sidebar; the right sidebar shows anchors on the current page.</p>",
      "anchors": []
    }
  }
};

export const docsByLocale: Record<DocLocale, Record<string, DocEntry>> = {
  "zh": {
    "software/getting-started": {
      "path": "software/getting-started",
      "meta": {
        "title": "快速开始",
        "description": "五分钟上手环回云",
        "order": 1,
        "navIgnore": false
      },
      "html": "<h1>快速开始</h1>\n<h2>安装</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">pnpm add loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">npm i loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2>配置</h2>\n<p>:::details[展开查看配置文件示例]</p>\n<pre><code class=\"language-toml\">[loopback]\naddr = \"127.0.0.1\"\n</code></pre>\n<p>:::</p>\n<p>:::warning\n不要把 <code>addr</code> 改成本机物理网卡地址，否则\"绝对安全\"卖点会失效。\n:::</p>",
      "anchors": []
    },
    "software/zh-only": {
      "path": "software/zh-only",
      "meta": {
        "title": "仅中文文档",
        "description": "用于回退测试",
        "order": 9,
        "navIgnore": false
      },
      "html": "<h1>仅中文文档</h1>\n<p>本文档故意只在中文版提供，用于验证缺失英文时的回退渲染。</p>",
      "anchors": []
    },
    "": {
      "path": "",
      "meta": {
        "title": "文档首页",
        "description": "环回云文档中心",
        "navIgnore": true
      },
      "html": "<h1>环回云文档</h1>\n<p>欢迎来到环回云文档中心。这里收录了产品使用指南、系统架构与开发文档。</p>\n<h2>导览</h2>\n<p>左侧栏按分类浏览，右侧栏显示当前页面锚点。</p>\n<p>:::note\n本站所有\"云服务\"均在 <code>127.0.0.1</code> 上运行。\n:::</p>",
      "anchors": []
    }
  },
  "en": {
    "software/getting-started": {
      "path": "software/getting-started",
      "meta": {
        "title": "Quick Start",
        "description": "Get going with Loopback Cloud in five minutes",
        "order": 1,
        "navIgnore": false
      },
      "html": "<h1>Quick Start</h1>\n<h2>Install</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">pnpm add loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre><code class=\"language-bash\">npm i loopback-cloud\n</code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2>Configuration</h2>\n<p>:::details[Expand for an example config]</p>\n<pre><code class=\"language-toml\">[loopback]\naddr = \"127.0.0.1\"\n</code></pre>\n<p>:::</p>\n<p>:::warning\nDo not change <code>addr</code> to a physical NIC, or the \"absolutely secure\" claim breaks.\n:::</p>",
      "anchors": []
    },
    "": {
      "path": "",
      "meta": {
        "title": "Docs Home",
        "description": "Loopback Cloud documentation",
        "navIgnore": true
      },
      "html": "<h1>Loopback Cloud Docs</h1>\n<p>Welcome to the Loopback Cloud documentation center.</p>\n<h2>Navigation</h2>\n<p>Browse categories in the left sidebar; the right sidebar shows anchors on the current page.</p>",
      "anchors": []
    }
  }
};

export const allDocPaths: string[] = [
  "",
  "software/getting-started",
  "software/zh-only"
];
