/* eslint-disable */
/* AUTO-GENERATED by scripts/build-docs.ts — do NOT edit by hand. */
import type {
  DocAnchor,
  DocCategoryNode,
  DocEntry,
  DocLocale,
  DocMeta,
  DocTree,
} from "~/lib/docs/types";

export type {
  DocAnchor,
  DocCategoryNode,
  DocEntry,
  DocLocale,
  DocMeta,
  DocTree,
};

export const trees: Record<DocLocale, DocTree> = {
  "zh": {
    "root": {
      "name": "root",
      "title": "root",
      "children": [
        {
          "name": "software",
          "title": "软件文档",
          "order": 1,
          "children": [],
          "docs": [
            {
              "path": "software/getting-started",
              "meta": {
                "title": "快速开始",
                "description": "五分钟上手环回云",
                "order": 1,
                "navIgnore": false
              },
              "html": "<h1 id=\"快速开始\">快速开始</h1>\n<h2 id=\"安装\">安装</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">pnpm</span><span style=\"color:#9ECBFF\"> add</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">npm</span><span style=\"color:#9ECBFF\"> i</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2 id=\"配置\">配置</h2>\n<p>:::details[展开查看配置文件示例]</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#E1E4E8\">[</span><span style=\"color:#B392F0\">loopback</span><span style=\"color:#E1E4E8\">]</span></span>\n<span class=\"line\"><span style=\"color:#E1E4E8\">addr = </span><span style=\"color:#9ECBFF\">\"127.0.0.1\"</span></span></code></pre>\n<p>:::</p>\n<p>:::warning\n不要把 <code>addr</code> 改成本机物理网卡地址，否则\"绝对安全\"卖点会失效。\n:::</p>",
              "anchors": [
                {
                  "id": "安装",
                  "text": "安装",
                  "level": 2
                },
                {
                  "id": "配置",
                  "text": "配置",
                  "level": 2
                }
              ]
            },
            {
              "path": "software/zh-only",
              "meta": {
                "title": "仅中文文档",
                "description": "用于回退测试",
                "order": 9,
                "navIgnore": false
              },
              "html": "<h1 id=\"仅中文文档\">仅中文文档</h1>\n<p>本文档故意只在中文版提供，用于验证缺失英文时的回退渲染。</p>",
              "anchors": []
            }
          ]
        }
      ],
      "docs": []
    },
    "indexDoc": {
      "path": "",
      "meta": {
        "title": "文档首页",
        "description": "环回云文档中心",
        "navIgnore": true
      },
      "html": "<h1 id=\"环回云文档\">环回云文档</h1>\n<p>欢迎来到环回云文档中心。这里收录了产品使用指南、系统架构与开发文档。</p>\n<h2 id=\"导览\">导览</h2>\n<p>左侧栏按分类浏览，右侧栏显示当前页面锚点。</p>\n<p>:::note\n本站所有\"云服务\"均在 <code>127.0.0.1</code> 上运行。\n:::</p>",
      "anchors": [
        {
          "id": "导览",
          "text": "导览",
          "level": 2
        }
      ]
    }
  },
  "en": {
    "root": {
      "name": "root",
      "title": "root",
      "children": [
        {
          "name": "software",
          "title": "Software Docs",
          "order": 1,
          "children": [],
          "docs": [
            {
              "path": "software/getting-started",
              "meta": {
                "title": "Quick Start",
                "description": "Get going with Loopback Cloud in five minutes",
                "order": 1,
                "navIgnore": false
              },
              "html": "<h1 id=\"quick-start\">Quick Start</h1>\n<h2 id=\"install\">Install</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">pnpm</span><span style=\"color:#9ECBFF\"> add</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">npm</span><span style=\"color:#9ECBFF\"> i</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2 id=\"configuration\">Configuration</h2>\n<p>:::details[Expand for an example config]</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#E1E4E8\">[</span><span style=\"color:#B392F0\">loopback</span><span style=\"color:#E1E4E8\">]</span></span>\n<span class=\"line\"><span style=\"color:#E1E4E8\">addr = </span><span style=\"color:#9ECBFF\">\"127.0.0.1\"</span></span></code></pre>\n<p>:::</p>\n<p>:::warning\nDo not change <code>addr</code> to a physical NIC, or the \"absolutely secure\" claim breaks.\n:::</p>",
              "anchors": [
                {
                  "id": "install",
                  "text": "Install",
                  "level": 2
                },
                {
                  "id": "configuration",
                  "text": "Configuration",
                  "level": 2
                }
              ]
            }
          ]
        }
      ],
      "docs": []
    },
    "indexDoc": {
      "path": "",
      "meta": {
        "title": "Docs Home",
        "description": "Loopback Cloud documentation",
        "navIgnore": true
      },
      "html": "<h1 id=\"loopback-cloud-docs\">Loopback Cloud Docs</h1>\n<p>Welcome to the Loopback Cloud documentation center.</p>\n<h2 id=\"navigation\">Navigation</h2>\n<p>Browse categories in the left sidebar; the right sidebar shows anchors on the current page.</p>",
      "anchors": [
        {
          "id": "navigation",
          "text": "Navigation",
          "level": 2
        }
      ]
    }
  }
};

export const docsByLocale: Record<DocLocale, Record<string, DocEntry>> = {
  "zh": {
    "software/getting-started": {
      "path": "software/getting-started",
      "meta": {
        "title": "快速开始",
        "description": "五分钟上手环回云",
        "order": 1,
        "navIgnore": false
      },
      "html": "<h1 id=\"快速开始\">快速开始</h1>\n<h2 id=\"安装\">安装</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">pnpm</span><span style=\"color:#9ECBFF\"> add</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">npm</span><span style=\"color:#9ECBFF\"> i</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2 id=\"配置\">配置</h2>\n<p>:::details[展开查看配置文件示例]</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#E1E4E8\">[</span><span style=\"color:#B392F0\">loopback</span><span style=\"color:#E1E4E8\">]</span></span>\n<span class=\"line\"><span style=\"color:#E1E4E8\">addr = </span><span style=\"color:#9ECBFF\">\"127.0.0.1\"</span></span></code></pre>\n<p>:::</p>\n<p>:::warning\n不要把 <code>addr</code> 改成本机物理网卡地址，否则\"绝对安全\"卖点会失效。\n:::</p>",
      "anchors": [
        {
          "id": "安装",
          "text": "安装",
          "level": 2
        },
        {
          "id": "配置",
          "text": "配置",
          "level": 2
        }
      ]
    },
    "software/zh-only": {
      "path": "software/zh-only",
      "meta": {
        "title": "仅中文文档",
        "description": "用于回退测试",
        "order": 9,
        "navIgnore": false
      },
      "html": "<h1 id=\"仅中文文档\">仅中文文档</h1>\n<p>本文档故意只在中文版提供，用于验证缺失英文时的回退渲染。</p>",
      "anchors": []
    },
    "": {
      "path": "",
      "meta": {
        "title": "文档首页",
        "description": "环回云文档中心",
        "navIgnore": true
      },
      "html": "<h1 id=\"环回云文档\">环回云文档</h1>\n<p>欢迎来到环回云文档中心。这里收录了产品使用指南、系统架构与开发文档。</p>\n<h2 id=\"导览\">导览</h2>\n<p>左侧栏按分类浏览，右侧栏显示当前页面锚点。</p>\n<p>:::note\n本站所有\"云服务\"均在 <code>127.0.0.1</code> 上运行。\n:::</p>",
      "anchors": [
        {
          "id": "导览",
          "text": "导览",
          "level": 2
        }
      ]
    }
  },
  "en": {
    "software/getting-started": {
      "path": "software/getting-started",
      "meta": {
        "title": "Quick Start",
        "description": "Get going with Loopback Cloud in five minutes",
        "order": 1,
        "navIgnore": false
      },
      "html": "<h1 id=\"quick-start\">Quick Start</h1>\n<h2 id=\"install\">Install</h2>\n<p>::::code-tabs</p>\n<p>:::tab{label=\"pnpm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">pnpm</span><span style=\"color:#9ECBFF\"> add</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>:::tab{label=\"npm\" lang=\"bash\"}</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#B392F0\">npm</span><span style=\"color:#9ECBFF\"> i</span><span style=\"color:#9ECBFF\"> loopback-cloud</span></span></code></pre>\n<p>:::</p>\n<p>::::</p>\n<h2 id=\"configuration\">Configuration</h2>\n<p>:::details[Expand for an example config]</p>\n<pre class=\"shiki github-dark\" style=\"background-color:#24292e;color:#e1e4e8\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color:#E1E4E8\">[</span><span style=\"color:#B392F0\">loopback</span><span style=\"color:#E1E4E8\">]</span></span>\n<span class=\"line\"><span style=\"color:#E1E4E8\">addr = </span><span style=\"color:#9ECBFF\">\"127.0.0.1\"</span></span></code></pre>\n<p>:::</p>\n<p>:::warning\nDo not change <code>addr</code> to a physical NIC, or the \"absolutely secure\" claim breaks.\n:::</p>",
      "anchors": [
        {
          "id": "install",
          "text": "Install",
          "level": 2
        },
        {
          "id": "configuration",
          "text": "Configuration",
          "level": 2
        }
      ]
    },
    "": {
      "path": "",
      "meta": {
        "title": "Docs Home",
        "description": "Loopback Cloud documentation",
        "navIgnore": true
      },
      "html": "<h1 id=\"loopback-cloud-docs\">Loopback Cloud Docs</h1>\n<p>Welcome to the Loopback Cloud documentation center.</p>\n<h2 id=\"navigation\">Navigation</h2>\n<p>Browse categories in the left sidebar; the right sidebar shows anchors on the current page.</p>",
      "anchors": [
        {
          "id": "navigation",
          "text": "Navigation",
          "level": 2
        }
      ]
    }
  }
};

export const allDocPaths: string[] = [
  "",
  "software/getting-started",
  "software/zh-only"
];
